### ISSUE TITLE
Allow wider figure captions

### ISSUE THREAD

**Issue by SimonBoothroyd** [openforcefield/openff-sphinx-theme#46]
By default the figure caption is limited to a width of 30 rem, but this can look a bit awkward for longer figure captions:

<img width="726" alt="image" src="https://user-images.githubusercontent.com/22272126/159673049-1406f21a-e354-486f-89cf-a1ebf3fd3d64.png">

Can we remove this limit? To me this looks a bit easier to read:

<img width="719" alt="image" src="https://user-images.githubusercontent.com/22272126/159673221-25e0724e-3c84-436f-b040-d8d942bf93f1.png">

**Comment by Yoshanuikabundi** [comment]
Yep, figure captions are left over from the Material design reset stylesheet, so this is easy to implement.
